services:
  theatre-db:
    image: postgres:13.10
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./data/dumps/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch_etl
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.audit.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    build: apps/postgres_to_es/migrator
    env_file:
      - .env
    networks:
      - etl_network
    volumes:
      - ./apps/common:/app/common
    depends_on:
      theatre-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  fastapi:
    build: apps/fast_api
    image: fastapi-image
    env_file:
      - .env
    networks:
      - etl_network
    ports:
      - "8000:8000"
    volumes:
      - ./apps/common:/app/src/common
    depends_on:
      theatre-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  tests:
    image: fastapi-image
    env_file:
      - .env
    entrypoint: >
      sh -c "pip install -r ../tests/functional/requirements.txt
      && pytest ../tests/functional/src"
    networks:
      - etl_network
    volumes:
      - ./apps/common:/app/common
    depends_on:
      theatre-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

networks:
  etl_network:
    driver: bridge

volumes:
  postgres_data:
  es_data: