"""Initial schema

Revision ID: 671d9c5d1ef5
Revises: 
Create Date: 2026-07-29 13:47:45.721516

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '671d9c5d1ef5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
